# Site settings
name: Long Blog
email: zhuoyuan1028@163.com
author: zilonglym
#url: http://www.hifreud.com
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/zilonglym/
baseurl: ""
description: Long as the way is I !
meta_description: 赵远;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zilonglym
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

#FB:
#  comments :
#    provider : duoshuo
#    duoshuo:
#        short_name : luoyan35714
#    disqus :
#        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light